### PR TITLE
Add option to set nested-link color

### PR DESCRIPTION
**Pull request by klzns**
Part of the code to generate the nested module is:

```css
.nested-links a {
  color: var(--blue);
  transition: color .15s ease-in;
}

.nested-links a:hover,
.nested-links a:focus {
  color: var(--light-blue);
  transition: color .15s ease-in;
}
```

So, if the user do not set the colors `blue` or `light-blue`, the following happens.

`light-blue` is not defined in colors:
```css
.nested-links a { color: #368df7; transition: color .15s ease-in; }
.nested-links a:hover { color: undefined; transition: color .15s ease-in; }
.nested-links a:focus { color: undefined; transition: color .15s ease-in; }
```

This PR adds the option to set the colors that will fill those values.

```json
"nested": {
  "links": ["blue", "light-blue"],
}
```

I'm only in doubt about this array.

I considered this option as well:
```json
"nested": {
  "links": {
    "default": "blue",
    "hoverFocus": "light-blue",
  }
}
```

But I didn't like the name `hoverFocus`. I'm open to suggestions.

### CODE REVIEW

**Comment by johnotander** [comment]
```
So, if the user do not set the colors blue or light-blue, the following happens.

light-blue is not defined in colors:
```

I think maybe we should fall back to the current Tachyons defaults (perhaps just as hardcoded hex values). That way we can maintain the existing behavior in case they remove those colors from the palette but don't update the links.

**Comment by klzns** [comment]
That's a good idea! I'll update this PR and the other one with this suggestion.

**Comment by klzns** [comment]
There you go!

One question: now that you assigned me as a project collaborator, what am I allowed to do and what are your expectations of me? I think that's important to be clear so I could contribute in the best way possible. Thanks!

**Comment by johno** [comment]
Thanks @klzns!

> One question: now that you assigned me as a project collaborator, what am I allowed to do and what are your expectations of me? I think that's important to be clear so I could contribute in the best way possible. Thanks!

The org is currently loosely structured and there are no particular expectations or obligations. With your new found powers you can merge any testing or docs changes at will. I only ask that you get a review from me or a new org member for new features and bugfixes.

And thanks for all your contributions so far!

**Pull request merged**
